# Component libraries are generated by SDC from each components/*/*.component.yml.
# The React runtime (react_scaffold/react, react_scaffold/react-api-client) comes from the base theme.
global-styling:
  css:
    theme:
      assets/global.css: {}
